version: '3.8'
services:
  equispe:
    build: https://github.com/Team-Lypus/Equispe.git
    image: equispe
    depends_on:
      - postgres
    environment:
      - TOKEN=YOUR DISCORD BOT TOKEN
      - CLIENT_ID=YOUR DISCORD APPLICATION ID
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DATABASE=root
      - PG_HOST=postgres
      - PG_PORT=5432
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=root
    volumes:
      - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql